-- Kaputei Farm Products — seed data (23 products)
-- Run AFTER supabase/schema.sql in the Supabase SQL editor.
-- Images are bare filenames: the site resolves them to the
-- product-images bucket automatically (see src/lib/supabase.ts).
-- Upload the matching PNGs to Storage → product-images first
-- (or do it after — cards simply show nothing until then... no,
-- cards fall back gracefully; the gradient tile always renders).
--
-- To reseed from scratch, uncomment the delete line below.
-- delete from products;

insert into products
  (id, name, handle, category, badge, price_kes, compare_at_price_kes,
   description_short, sizes, variants, images,
   gradient_from, gradient_to, sort_order)
values
  ('barbecue-sauce', 'Barbecue Sauce', 'barbecue-sauce', 'Sauces', null, 148.57, 179.00,
   'Smoky, sweet, tangy BBQ sauce. Mild with a smoky kick.',
   array['250g','400g','700g','1kg'], array['Original','Honey','Sweet and Sticky','Smoke'],
   array['barbecue-sauce.png','barbecue-sauce-back.png','barbecue-sauce-original.png','barbecue-sauce-honey.png','barbecue-sauce-sweet-and-sticky.png','barbecue-sauce-smoke.png'],
   '#7B3A18', '#C8252C', 1),
  ('cheese-sauce', 'Cheese Sauce', 'cheese-sauce', 'Sauces', null, 355.49, null,
   'Smooth, creamy, rich cheese flavor. Great for nachos, fries, burgers, pasta.',
   array['375g'], array[]::text[],
   array['cheese-sauce.png'],
   '#E8B93E', '#C8941F', 2),
  ('chilli-sauce', 'Chilli Sauce', 'chilli-sauce', 'Sauces', null, 64.46, null,
   'Fiery blend of sun-ripened chillies, garlic and spices. Medium-high heat.',
   array['250g','400g'], array['Chilli','Hot Chilli'],
   array['chilli-sauce.png','chilli-sauce-chilli.png','chilli-sauce-hot-chilli.png'],
   '#C8252C', '#5A0E12', 3),
  ('choma-sauce', 'Choma Sauce', 'choma-sauce', 'Sauces', null, 139.93, null,
   'Bold, smoky, Kenyan-style sauce for nyama choma, hotdogs, roasted chicken, smochas.',
   array['400g'], array[]::text[],
   array['choma-sauce.png','choma-sauce-back.png'],
   '#D94B2B', '#7B3A18', 4),
  ('chutney', 'Chutney', 'chutney', 'Chutney', null, 399.44, 430.00,
   'Passion Fruit Chutney (mild-medium heat) and Mango Chutney (mild).',
   array['360g'], array['Passion Fruit','Mango'],
   array['chutney.png','chutney-passion-fruit.png','chutney-mango.png'],
   '#C8941F', '#5C8A3A', 5),
  ('honey', 'Honey', 'honey', 'Pantry', null, 267.67, 291.00,
   '100% pure, raw, unfiltered natural honey. No additives.',
   array['300g','500g','450g','1kg','2kg'], array['Honey Premium','Honey Premium Squeeze','Select Honey','Natural Honey'],
   array['honey.png','honey-premium.png','honey-premium-squeeze.png','honey-select.png','honey-natural.png'],
   '#E8B93E', '#B8721A', 6),
  ('hot-sweet-sauce', 'Hot & Sweet Sauce', 'hot-sweet-sauce', 'Sauces', 'Popular', 88.41, null,
   'Balance of bold heat and rich sweetness. Great for glazing, dipping, marinating.',
   array[]::text[], array[]::text[],
   array['hot-sweet-sauce.png'],
   '#E07A1F', '#C8252C', 7),
  ('hotels-catering', 'Hotels & Catering', 'hotels-catering', 'Bulk', 'Bulk', 222.58, 259.00,
   'Bulk hospitality range: house sauces in 2l/5l/20l packs for hotels, restaurants, caterers.',
   array['2l','5l','20l'], array['Tomato Sauce','Tomato Ketchup','BBQ Sauce','Choma Sauce','Chilli Sauce','1000 Island','Chipotle','Cool Ranch','Honey Mustard','Teriyaki','Mayonnaise','Eggless Mayonnaise'],
   array['hotels-catering.png','hotels-catering-tomato-sauce.png','hotels-catering-tomato-ketchup.png','hotels-catering-bbq-sauce.png','hotels-catering-choma-sauce.png','hotels-catering-chilli-sauce.png'],
   '#1F1A17', '#7B3A18', 8),
  ('jalapenos', 'Jalapeños', 'jalapenos', 'Pickles', null, 312.84, 367.00,
   'Pickled, sliced jalapeños. Medium heat.',
   array['350g','700g'], array[]::text[],
   array['jalapenos.png'],
   '#5C8A3A', '#2E4D1F', 9),
  ('jams', 'Jams', 'jams', 'Spreads', null, 313.79, 349.00,
   'Strawberry, Red Plum, Passion Fruit, Orange Marmalade, Blueberry, Blackberry jams.',
   array['214g','400g'], array['Strawberry','Red Plum','Passion Fruit','Orange Marmalade','Blueberry','Blackberry'],
   array['jams.png','jams-strawberry.png','jams-passion-fruit.png','jams-orange-marmalade.png','jams-red-plum.png','jams-blackberry.png','jams-blueberry.png'],
   '#C8252C', '#5C8A3A', 10),
  ('mayonnaise', 'Mayonnaise', 'mayonnaise', 'Sauces', null, 319.55, null,
   'Smooth & Creamy / Sweet & Tangy mayo duo, plus Eggless, Vegan, Garlic options.',
   array['350g','700g','1.9kg'], array['Smooth & Creamy','Sweet & Tangy','Eggless','Vegan','Garlic'],
   array['mayonnaise.png','mayonnaise-smooth-creamy.png','mayonnaise-eggless.png','mayonnaise-vegan.png','mayonnaise-garlic.png'],
   '#F5E6C8', '#D9B98A', 11),
  ('mustard', 'Mustard', 'mustard', 'Sauces', null, 200.59, 229.00,
   'Classic bold, tangy mustard and Honey Mustard.',
   array['250g','400g'], array['Mustard','Honey Mustard'],
   array['mustard.png','mustard-classic.png','mustard-honey.png'],
   '#E8B93E', '#C8941F', 12),
  ('pasta-sauces', 'Pasta Sauces', 'pasta-sauce', 'Sauces', null, 355.49, 389.00,
   'Gourmet pasta sauces: Regular, Basil, Garlic, Hot, Mushroom, Spaghetti, Bolognaise, Lasagna, Cheese.',
   array['375g','650g'], array['Regular','Basil','Garlic','Hot','Mushroom','Spaghetti','Bolognaise','Lasagna','Cheese'],
   array['pasta-sauces.png','pasta-sauces-regular.png','pasta-sauces-basil.png','pasta-sauces-garlic.png','pasta-sauces-hot.png','pasta-sauces-mushroom.png','pasta-sauces-spaghetti.png','pasta-sauces-bolognaise.png','pasta-sauces-lasagna.png','pasta-sauces-cheese.png'],
   '#C8252C', '#9E1B22', 13),
  ('pestos', 'Pestos', 'pestos', 'Sauces', null, 341.97, 399.00,
   'Roasted Pepper, Coriander, Basil, Rocket (Arugula), Sun-Dried Tomato pesto.',
   array['190g'], array['Roasted Pepper','Coriander','Basil','Rocket','Sundried Tomato'],
   array['pestos.png','pestos-roasted-pepper.png','pestos-basil.png','pestos-coriander.png','pestos-rocket.png','pestos-sundried-tomato.png'],
   '#5C8A3A', '#2E4D1F', 14),
  ('pickles', 'Pickles', 'pickles', 'Pickles', null, 308.61, null,
   'Pickled Gherkins (whole/sliced) and Sweet Dill Pickles.',
   array['300g','700g'], array['Pickled Gherkins','Sliced Gherkins','Sweet Dill'],
   array['pickles.png','pickles-gherkins.png','pickles-sliced-gherkins.png','pickles-sweet-dill.png'],
   '#7BA05A', '#4A6B2F', 15),
  ('pizza-sauce', 'Pizza Sauce', 'pizza-sauce', 'Sauces', null, 355.49, 389.00,
   'Rich, tangy pizza sauce — Regular and Hot.',
   array['375g','650g'], array['Regular','Hot'],
   array['pizza-sauce.png','pizza-sauce-regular.png','pizza-sauce-hot.png'],
   '#C8252C', '#E07A1F', 16),
  ('salad-dressings', 'Salad Dressings', 'salad-dressings', 'Dressings', null, 204.96, 229.00,
   '1000 Island, Chipotle, Cool Ranch, Teriyaki, Mayo Ketchup, Herb Vinaigrette, Sweet Onion, Tartar, Sesame Goma.',
   array['250g','400g'], array['1000 Island','Cool Ranch','Teriyaki','Mayo Ketchup','Herb Vinaigrette','Sweet Onion','Tartar','Chipotle','Roasted Sesame Goma'],
   array['salad-dressings.png','salad-dressings-1000-island.png','salad-dressings-cool-ranch.png','salad-dressings-teriyaki.png','salad-dressings-mayo-ketchup.png','salad-dressings-herb-vinaigrette.png','salad-dressings-sweet-onion.png','salad-dressings-tartar.png','salad-dressings-chipotle.png','salad-dressings-roasted-sesame-goma.png'],
   '#F5E6C8', '#C8941F', 17),
  ('salsa-kachumbari', 'Salsa Kachumbari', 'salsa-kachumbari', 'Sauces', 'Kenyan classic', 266.33, null,
   'Fresh Kenyan-style tomato, onion, chilli and herb salsa.',
   array['400g'], array[]::text[],
   array['salsa-kachumbari.png'],
   '#D94B2B', '#C8252C', 18),
  ('sundried-tomatoes', 'Sundried Tomatoes', 'sundried-tomatoes', 'Pantry', null, 394.62, 449.00,
   'Sun-dried tomatoes marinated in olive oil and herbs.',
   array['285g','550g'], array[]::text[],
   array['sundried-tomatoes.png'],
   '#C8252C', '#7B3A18', 19),
  ('teas', 'Herbal Teas', 'teas', 'Teas', null, 222.07, 245.00,
   'Hibiscus, Chamomile, Moringa, Avocado Leaf, Peppermint, Lemon Symphony, Green & Black teas.',
   array['25pcs*1.5g','25pcs*2g','25pcs*1.9g','100pcs*2g'], array['Chamomile','Moringa','Hibiscus','Avocado','Peppermint','Lemon Symphony','Green Tea','Avocado Lemongrass','Black Tea Blend','Variety Pack'],
   array['teas.png','teas-chamomile.png','teas-moringa.png','teas-hibiscus.png','teas-avocado.png','teas-variety-pack.png','teas-peppermint.png','teas-lemon-symphony.png','teas-green-tea.png','teas-avocado-lemongrass.png','teas-black-tea-blend.png'],
   '#5C8A3A', '#8A5A3A', 20),
  ('tomato-ketchup', 'Tomato Ketchup', 'tomato-ketchup', 'Sauces', null, 110.43, 129.00,
   'Classic tangy tomato ketchup, made from sun-ripened tomatoes.',
   array['250g','400g','700g'], array[]::text[],
   array['tomato-ketchup.png','tomato-ketchup-back.png'],
   '#C8252C', '#9E1B22', 21),
  ('tomato-sauce', 'Tomato Sauce', 'tomato-sauce', 'Sauces', 'Bestseller', 61.55, 70.00,
   'Smooth, slow-cooked everyday tomato sauce. Thicker than puree, lighter than ketchup.',
   array['250g','400g','700g','1kg'], array[]::text[],
   array['tomato-sauce.png'],
   '#C8252C', '#5A0E12', 22),
  ('worcestershire-sauce', 'Worcestershire Sauce', 'worcestershire-sauce', 'Sauces', null, 347.91, 549.00,
   'Tangy vinegar, molasses, tamarind and spice blend. Umami-rich.',
   array['250g','400g'], array[]::text[],
   array['worcestershire-sauce.png','worcestershire-sauce-back.png'],
   '#4A2518', '#1F1A17', 23);
